package main

import (
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"sync"
	"time"

	"github.com/joho/godotenv"
)

// ApiRequest stores parameters for specific geographic regions and data types.
type ApiRequest struct {
	Country      string
	Domain       string
	DocumentType string
	ProcessType  string
	FeatureName  string
}

// A global HTTP client is configured with an extended timeout to prevent I/O timeouts.
var client = &http.Client{
	Timeout: 60 * time.Second,
}

// fetchENTSOE orchestrates the network request, parameter routing, and network resilience.
func fetchENTSOE(req ApiRequest, token string, wg *sync.WaitGroup, limiter chan struct{}) {
	defer wg.Done()
	defer func() { <-limiter }()

	outputPath := fmt.Sprintf("../../../data/raw/%s_%s.csv", req.Country, req.FeatureName)
	periodStart := "202601010000"
	periodEnd := "202604012300"

	// The URL is dynamically constructed to ensure compliance with API requirements.
	url := fmt.Sprintf("https://web-api.tp.entsoe.eu/api?securityToken=%s&documentType=%s&periodStart=%s&periodEnd=%s",
		token, req.DocumentType, periodStart, periodEnd)

	if req.DocumentType == "A44" {
		url += fmt.Sprintf("&in_Domain=%s&out_Domain=%s", req.Domain, req.Domain)
	} else if req.DocumentType == "A65" {
		url += fmt.Sprintf("&outBiddingZone_Domain=%s", req.Domain)
	} else {
		url += fmt.Sprintf("&in_Domain=%s", req.Domain)
	}

	if req.ProcessType != "" {
		url += "&processType=" + req.ProcessType
	}

	fmt.Printf("Requesting %s for %s...\n", req.FeatureName, req.Country)

	// RETRY MECHANISM: The system will attempt the network request up to 3 times before failing.
	maxRetries := 3
	for attempt := 1; attempt <= maxRetries; attempt++ {
		resp, err := client.Get(url)

		if err != nil {
			if attempt < maxRetries {
				fmt.Printf("Network drop for %s %s (Attempt %d/%d). Retrying in 5s...\n", req.Country, req.FeatureName, attempt, maxRetries)
				time.Sleep(5 * time.Second) // Pause to allow network packet loss to clear
				continue
			}
			fmt.Printf("Fatal Network Error for %s %s after %d attempts: %v\n", req.Country, req.FeatureName, maxRetries, err)
			return
		}

		defer resp.Body.Close()

		if resp.StatusCode == 200 {
			body, _ := io.ReadAll(resp.Body)
			err = ParseAndSaveCSV(body, outputPath)
			if err != nil {
				fmt.Printf("Parsing failed for %s %s: %v\n", req.Country, req.FeatureName, err)
			} else {
				fmt.Printf("Success. Saved %s_%s\n", req.Country, req.FeatureName)
			}
		} else {
			// Captures 400 or 503 HTTP errors generated by the server.
			body, _ := io.ReadAll(resp.Body)
			fmt.Printf("HTTP %d Error for %s %s: %s\n", resp.StatusCode, req.Country, req.FeatureName, string(body))
		}

		// Escapes the retry loop following a successful HTTP transaction.
		break
	}

	// A mandatory delay ensures adherence to server-side rate limits.
	time.Sleep(3 * time.Second)
}

func main() {
	start := time.Now()
	fmt.Println("Starting Full Pan-European Data Ingestion (2026 YTD)...")

	err := godotenv.Load("../../../.env")
	if err != nil {
		log.Fatal("Environment file loading failed.")
	}

	token := os.Getenv("ENTSOE_API_KEY")

	countries := []struct{ Name, Code string }{
		{"Austria", "10YAT-APG------L"}, {"Belgium", "10YBE----------2"},
		{"Bulgaria", "10YCA-BULGARIA-R"}, {"Croatia", "10YHR-HEP------M"},
		{"CzechRepublic", "10YCZ-CEPS-----N"}, {"Denmark", "10YDK-1--------W"},
		{"Estonia", "10Y1001A1001A39I"}, {"Finland", "10YFI-1--------U"},
		{"France", "10YFR-RTE------C"}, {"Germany", "10Y1001A1001A82H"},
		{"Greece", "10YGR-HTSO-----Y"}, {"Hungary", "10YHU-MAVIR----U"},
		{"Ireland", "10Y1001A1001A597"}, {"Italy", "10Y1001A1001A73I"},
		{"Latvia", "10YLV-1001A00074"}, {"Lithuania", "10YLT-1001A0008Q"},
		{"Netherlands", "10YNL----------L"}, {"Norway", "10YNO-1--------2"},
		{"Poland", "10YPL-AREA-----S"}, {"Portugal", "10YPT-REN------W"},
		{"Romania", "10YRO-TEL------P"}, {"Slovakia", "10YSK-SEPS-----K"},
		{"Slovenia", "10YSI-ELES-----O"}, {"Spain", "10YES-REE------0"},
		{"Sweden", "10Y1001A1001A46L"}, {"Switzerland", "10YCH-SWISSGRIDZ"},
	}

	features := []struct{ Doc, Proc, Name string }{
		{"A44", "", "Prices"},
		{"A75", "A16", "Actual_Generation"},
		{"A65", "A16", "Actual_Load"},
		{"A65", "A01", "Forecast_Load"},
		{"A69", "A01", "Forecast_WindSolar"},
	}

	var wg sync.WaitGroup

	// The semaphore restricts execution to two concurrent requests to prevent triggering IP-based rate limiting.
	limiter := make(chan struct{}, 2)

	for _, c := range countries {
		for _, f := range features {
			wg.Add(1)
			limiter <- struct{}{}
			go fetchENTSOE(ApiRequest{c.Name, c.Code, f.Doc, f.Proc, f.Name}, token, &wg, limiter)
		}
	}

	wg.Wait()
	fmt.Printf("Full extraction completed in %s\n", time.Since(start))
}
