package main

import (
	"context"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/s3"
	"github.com/joho/godotenv"
)

const (
	bucketName = "eu-energy-raw-ireland-sj"
	region     = "eu-west-1"
	dataDir    = "../../../data/raw" // Correctly navigates up to the root, then into data/raw
	s3Prefix   = "bronze/"           // The target folder inside S3
)

// uploadFile handles the streaming of a single file to AWS S3 with dynamic folder mapping
func uploadFile(ctx context.Context, client *s3.Client, filePath string, wg *sync.WaitGroup, limiter chan struct{}) {
	defer wg.Done()
	defer func() { <-limiter }()

	file, err := os.Open(filePath)
	if err != nil {
		log.Printf("Failed to open file %s: %v\n", filePath, err)
		return
	}
	defer file.Close()

	fileName := filepath.Base(filePath)
	var subFolder string

	// Dynamically determine the sub-folder path based on the feature name type
	if strings.Contains(fileName, "Prices") {
		subFolder = "prices/"
	} else if strings.Contains(fileName, "Actual_Load") {
		subFolder = "actual_load/"
	} else if strings.Contains(fileName, "Forecast_Load") {
		subFolder = "forecast_load/"
	} else if strings.Contains(fileName, "Actual_Generation") {
		subFolder = "actual_generation/"
	} else if strings.Contains(fileName, "Forecast_WindSolar") {
		subFolder = "forecast_wind_solar/"
	} else if strings.Contains(fileName, "weather") {
		subFolder = "weather/"
	} else {
		subFolder = "misc/"
	}

	s3Key := s3Prefix + subFolder + fileName

	_, err = client.PutObject(ctx, &s3.PutObjectInput{
		Bucket: aws.String(bucketName),
		Key:    aws.String(s3Key),
		Body:   file,
	})

	if err != nil {
		log.Printf("Failed to upload %s: %v\n", fileName, err)
	} else {
		fmt.Printf("Successfully uploaded %s to s3://%s/%s\n", fileName, bucketName, s3Key)
	}
}

func main() {
	start := time.Now()
	fmt.Println("Starting S3 Bulk Upload to Bronze Layer...")

	// Load credentials from your existing .env setup in the root directory
	err := godotenv.Load("../../../.env")
	if err != nil {
		log.Println("No .env file found. Falling back to system environment variables.")
	}

	// Initialize the AWS Client in the correct region (Ireland)
	cfg, err := config.LoadDefaultConfig(context.TODO(), config.WithRegion(region))
	if err != nil {
		log.Fatalf("Unable to load AWS SDK config: %v", err)
	}

	client := s3.NewFromConfig(cfg)
	var wg sync.WaitGroup

	// A semaphore to limit concurrent uploads to 5 to avoid overwhelming network buffers
	limiter := make(chan struct{}, 5)

	// Read all files generated by your fetch script
	files, err := os.ReadDir(dataDir)
	if err != nil {
		log.Fatalf("Failed to read directory %s: %v", dataDir, err)
	}

	uploadCount := 0
	for _, file := range files {
		// Only upload .csv files
		if !file.IsDir() && filepath.Ext(file.Name()) == ".csv" {
			uploadCount++
			wg.Add(1)
			limiter <- struct{}{}

			filePath := filepath.Join(dataDir, file.Name())
			go uploadFile(context.TODO(), client, filePath, &wg, limiter)
		}
	}

	wg.Wait()
	fmt.Printf("Bulk upload completed! %d files transferred in %s\n", uploadCount, time.Since(start))
}
