package main

import (
	"context"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/s3"
	"github.com/aws/aws-sdk-go-v2/service/s3/types"
	"github.com/joho/godotenv"
)

const (
	bucketName = "eu-energy-raw-ireland-sj"
	region     = "eu-west-1"
	dataDir    = "../../../data/raw" // Correctly navigates up to the root, then into data/raw
	s3Prefix   = "bronze/"           // The target folder inside S3
)

// emptyBronzeLayer deletes all existing objects in the target S3 prefix before uploading new data
func emptyBronzeLayer(ctx context.Context, client *s3.Client) {
	fmt.Printf("Scanning s3://%s/%s for existing files...\n", bucketName, s3Prefix)
	paginator := s3.NewListObjectsV2Paginator(client, &s3.ListObjectsV2Input{
		Bucket: aws.String(bucketName),
		Prefix: aws.String(s3Prefix),
	})

	var objectIds []types.ObjectIdentifier

	for paginator.HasMorePages() {
		page, err := paginator.NextPage(ctx)
		if err != nil {
			log.Fatalf("Failed to list objects in bucket: %v", err)
		}

		for _, obj := range page.Contents {
			objectIds = append(objectIds, types.ObjectIdentifier{Key: obj.Key})
		}
	}

	if len(objectIds) > 0 {
		fmt.Printf("Found %d old files. Deleting...\n", len(objectIds))
		// AWS allows deleting up to 1000 objects per request
		for i := 0; i < len(objectIds); i += 1000 {
			end := i + 1000
			if end > len(objectIds) {
				end = len(objectIds)
			}

			_, err := client.DeleteObjects(ctx, &s3.DeleteObjectsInput{
				Bucket: aws.String(bucketName),
				Delete: &types.Delete{
					Objects: objectIds[i:end],
					Quiet:   aws.Bool(true),
				},
			})
			if err != nil {
				log.Fatalf("Failed to delete objects: %v", err)
			}
		}
		fmt.Println("Bronze layer successfully cleared.")
	} else {
		fmt.Println("Bronze layer is already empty.")
	}
}

// uploadFile handles the streaming of a single file to AWS S3 with dynamic folder mapping
func uploadFile(ctx context.Context, client *s3.Client, filePath string, wg *sync.WaitGroup, limiter chan struct{}) {
	defer wg.Done()
	defer func() { <-limiter }()

	file, err := os.Open(filePath)
	if err != nil {
		log.Printf("Failed to open file %s: %v\n", filePath, err)
		return
	}
	defer file.Close()

	fileName := filepath.Base(filePath)
	var subFolder string

	// Dynamically determine the sub-folder path based on the feature name type
	if strings.Contains(fileName, "Prices") {
		subFolder = "prices/"
	} else if strings.Contains(fileName, "Actual_Load") {
		subFolder = "actual_load/"
	} else if strings.Contains(fileName, "Forecast_Load") {
		subFolder = "forecast_load/"
	} else if strings.Contains(fileName, "Actual_Generation") {
		subFolder = "actual_generation/"
	} else if strings.Contains(fileName, "Forecast_WindSolar") {
		subFolder = "forecast_wind_solar/"
	} else if strings.Contains(fileName, "weather") {
		subFolder = "weather/"
	} else {
		subFolder = "misc/"
	}

	s3Key := s3Prefix + subFolder + fileName

	_, err = client.PutObject(ctx, &s3.PutObjectInput{
		Bucket: aws.String(bucketName),
		Key:    aws.String(s3Key),
		Body:   file,
	})

	if err != nil {
		log.Printf("Failed to upload %s: %v\n", fileName, err)
	} else {
		fmt.Printf("Successfully uploaded %s to s3://%s/%s\n", fileName, bucketName, s3Key)
	}
}

func main() {
	start := time.Now()
	fmt.Println("Starting DataOps S3 Pipeline...")

	// Load credentials from your existing .env setup in the root directory
	err := godotenv.Load("../../../.env")
	if err != nil {
		log.Println("No .env file found. Falling back to system environment variables.")
	}

	// Initialize the AWS Client in the correct region (Ireland)
	cfg, err := config.LoadDefaultConfig(context.TODO(), config.WithRegion(region))
	if err != nil {
		log.Fatalf("Unable to load AWS SDK config: %v", err)
	}

	client := s3.NewFromConfig(cfg)

	// STEP 1: Empty the existing Bronze layer to ensure a clean slate
	emptyBronzeLayer(context.TODO(), client)

	// STEP 2: Blast the new files up to the cloud
	fmt.Println("Starting S3 Bulk Upload to Bronze Layer...")
	var wg sync.WaitGroup

	// A semaphore to limit concurrent uploads to 5 to avoid overwhelming network buffers
	limiter := make(chan struct{}, 5)

	// Read all files generated by your fetch script
	files, err := os.ReadDir(dataDir)
	if err != nil {
		log.Fatalf("Failed to read directory %s: %v", dataDir, err)
	}

	uploadCount := 0
	for _, file := range files {
		// Only upload .csv files
		if !file.IsDir() && filepath.Ext(file.Name()) == ".csv" {
			uploadCount++
			wg.Add(1)
			limiter <- struct{}{}

			filePath := filepath.Join(dataDir, file.Name())
			go uploadFile(context.TODO(), client, filePath, &wg, limiter)
		}
	}

	wg.Wait()
	fmt.Printf("Bulk upload completed! %d files transferred in %s\n", uploadCount, time.Since(start))
}
